AWSTemplateFormatVersion: '2010-09-09'

Resources:
  MyVPC1:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16

  MyIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3AccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:GetObject
                  - s3:PutObject
                  - iam:*
                  - ec2:CreateNetworkInterface
                  - ec2:DescribeNetworkInterfaces
                  - ec2:DeleteNetworkInterface
                  - rds:DescribeDBProxies
                  - rds:DescribeDBProxyTargets
                  - rds-db:connect
                Resource: '*'

  MyBucketSL1Policy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MyBucketSL1
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !GetAtt MyIAMRole.Arn
            Action:
              - s3:ListBucket
              - s3:GetObject
              - s3:PutObject
            Resource:
              - !Sub arn:aws:s3:::${MyBucketSL1}
              - !Sub arn:aws:s3:::${MyBucketSL1}/*

  MyBucketSL1:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-bucket-sl-1

  MyInternetGateway:
    Type: AWS::EC2::InternetGateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref MyVPC1
      InternetGatewayId: !Ref MyInternetGateway

Outputs:

  MyIAMRoleArn:
    Description: ARN of the IAM Role for Lambda access
    Value: !GetAtt MyIAMRole.Arn
    Export:
      Name: s3-MyIAMRole

  MyVPCArn:
    Description: ARN of the VPC
    Value: !Ref MyVPC1
    Export:
      Name: s3-MyVPC1

  MyBucketSL1Arn:
    Description: ARN of the s3 bucket
    Value: !Ref MyBucketSL1
    Export:
      Name: s3-MyBucketSL1