AWSTemplateFormatVersion: '2010-09-09'

Resources:

  MyApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: MyServerlessAppAPI

  SubmitNameResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt MyApiGateway.RootResourceId
      PathPart: submit-name
      RestApiId: !Ref MyApiGateway

  SubmitNameMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref MyApiGateway
      ResourceId: !Ref SubmitNameResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri: !Sub
          - arn:aws:apigateway:${Region}:lambda:path/2015-03-31/functions/${LambdaArn}/invocations
          - Region: !Ref "AWS::Region"
            LambdaArn: !Ref Lambda-ref
      MethodResponses:
        - StatusCode: 200

  MyLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref Lambda-ref
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub
        arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${MyApiGateway}/*/POST/submit-name

  MyApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: SubmitNameMethod
    Properties:
      RestApiId: !Ref MyApiGateway
      StageName: prod

  EnableCorsMethodSetting:
    Type: AWS::ApiGateway::MethodSettings
    Properties:
      MethodSetting:
        ResourcePath: "/*"
        HttpMethod: POST
        Settings:
          CacheDataEncrypted: false
          CacheTtlInSeconds: 0
          CachingEnabled: false
          DataTraceEnabled: true
          LoggingLevel: INFO
          MetricsEnabled: true
          ThrottlingBurstLimit: 100
          ThrottlingRateLimit: 50
Outputs:
  ApiUrl:
    Description: "The URL of the API Gateway endpoint"
    Value: !Sub "https://${MyApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod"
